DROP TABLE IF EXISTS ip_address;
DROP SEQUENCE IF EXISTS ip_address_id;
DROP TABLE IF EXISTS migration;
DROP SEQUENCE IF EXISTS migration_id;
DROP TABLE IF EXISTS session;
DROP SEQUENCE IF EXISTS session_id;
DROP TABLE IF EXISTS cookie ;
DROP SEQUENCE IF EXISTS cookie_id;